### ISSUE TITLE
Input visibility

### ISSUE THREAD

**Issue by crespire** [radiushq/feature-requests#12]
I have dark mode enabled, and had a heck of a time figuring out what was going on with the Trix URL input:
![image](https://github.com/radiushq/feature-requests/assets/36272822/49b3f13c-a04a-4c53-adee-db6cffe1c69d)

Turns out, it was white text on a white background which was the problem.

**Comment by smuui** [comment]
Thanks for reporting @crespire!  

Resolved in the latest release 📝
