### ISSUE TITLE
[Bug] Upcoming events counter shows wrong value

### ISSUE THREAD

**Issue by stefanbc** [radiushq/feature-requests#13]
Even though there are no upcoming events

![Screenshot 2024-01-19 at 9 55 48 AM](https://github.com/radiushq/feature-requests/assets/1278794/f63d72fc-1656-4aff-85cb-48e0743fefec)

the counter on the group page under the name says there are

![Screenshot 2024-01-19 at 9 56 04 AM](https://github.com/radiushq/feature-requests/assets/1278794/526e587d-dbcc-4c11-8226-489a4c5cd8d6)

**Comment by smuui** [comment]
Thanks for highlighting @stefanbc!  

Past events were included in this count by mistake - I've fixed this in the latest release 👍
