### ISSUE TITLE
Unlisted Event

### ISSUE THREAD

**Issue by crespire** [radiushq/feature-requests#14]
Thanks so much for your work on the draft event - it's awesome. I was wondering if it would be a big lift to do an "unlisted" status too, kind of like Youtube videos.

1. Draft is not published, nor accessible publicly
2. Unlisted is not published, but accessible if someone has the right link
3. Published

**Comment by smuui** [comment]
Oh interesting - that's one I hadn't considered before!  

So, a few immediate questions on this:-

1. What would the motivations/use case be for an unlisted event?  Is it just a slightly easier to access page than what would be a private event (mentioned below - you'd need to be logged in and a member to view those in the future).
2. Where would the listing be visible from and to whom - i.e. I guess the organiser would be able to see it on the groups page.  Would logged in group members be able to see the listing on the group page too, or would they need to visit the link directly?
3. Would this be OK to be indexed by Google?  Currently our events are picked up by Google and listed on their events page - we have a sitemap file that's updated daily but could easily filter out unlisted events from this.

We currently have a `status` enum on the Event which includes `published` and `draft`.  Initial thoughts are this would be in a separate enum - maybe `visibility` - with `unlisted`, `public`, and in the future, `private`.  I'm thinking this would be best as a dropdown with these three options.

**Additional note:** private events and groups are on the future feature list - i.e. only visible to logged in group members.  Just mentioning in case there's some crossover in the functionality you'd like there.  If it's exactly like Youtube videos then I guess private and unlisted are completely different so disregard this comment if that's the case!

Thanks for another useful request! 🙏 🚀

**Comment by crespire** [comment]
> Oh interesting - that's one I hadn't consider before!
> 
> So, a few immediate questions on this:-
> 
>     1. What would the motivations/use case be for an unlisted event?  Is it just a slightly easier to access page than what would be a private event (mentioned below - you'd need to be logged in and a member to view those in the future).
> 
>     2. Where would the listing be visible from and to whom - i.e. I guess the organiser would be able to see it on the groups page.  Would logged in group members be able to see the listing on the group page too, or would they need to visit the link directly?
> 
>     3. Would this be OK to be indexed by Google?  Currently our events are picked up by Google and listed on their events page - we have a sitemap file that's updated daily but could easily filter out unlisted events from this.
> 
> 
> We currently have a `status` enum on the Event which includes `published` and `draft`. Initial thoughts are this would be in a separate enum - maybe `visibility` - with `unlisted`, `public`, and in the future, `private`. I'm thinking this would be best as a dropdown with these three options.
> 
> **Additional note:** private events and groups are on the future feature list - i.e. only visible to logged in group members. Just mentioning in case there's some crossover in the functionality you'd like there. If it's exactly like Youtube videos then I guess private and unlisted are completely different so disregard this comment if that's the case!
> 
> Thanks for another useful request! 🙏 🚀

1. My main motivation is to be able to send the event to a speaker so they can confirm the copy, etc without me sharing a screenshot, and not having the event be public as well.
2. I think only the organizers and those with the link would be able to see the event in an "unlisted" status. This, I think, reduces the complexity around potential members only events, as you could publish the event, but then scope access to "group members only" as a separate thing.  I think your separate enum is exactly what I was thinking.
3. I think having unlisted events skip indexing would be ideal.

**Comment by smuui** [comment]
Thanks again for the request @crespire!  

Unlisted events have now been added in the latest release.  Implementation is slightly different from above in that the draft/published states are separate from the listing state, so a published event can be either unlisted or listed.  In the future I'll add a private state where only logged in group members can view the event.

Let me know if you have any issues if you get a chance to try it out at some point!
