### ISSUE TITLE
Daylight Savings Time Bug

### ISSUE THREAD

**Issue by crespire** [radiushq/feature-requests#15]
Entered information in the form for creating/editing event:
![image](https://github.com/radiushq/feature-requests/assets/36272822/943b4dc0-1a5b-499c-bc99-73930b321ad0)

Displayed time:
![image](https://github.com/radiushq/feature-requests/assets/36272822/f53d7234-98d1-42fd-af59-10c45ce9dca1)

I have to enter the times offset by 1 hour to get the correct display. The calendar export is fine, so I think the problem is the input timezone is not DST aware. No trouble, as the display side and calendar export work as expected.

If you do fix this, please let me know so I can update the event!

Curiously, the times load correctly when I go back to edit the form (ie, it loads as 6pm to 9pm), so there's some transformation that happens on create/update.

**Comment by smuui** [comment]
Pesky daylight savings..  Good spot @crespire - thanks very much for reporting this 🙏 

Will let you know when this is resolved!

**Comment by smuui** [comment]
Thanks for your patience with this @crespire!  This was resolved in a previous release so should hopefully be working fine now.

LMK if you have any further time related issues!
