### ISSUE TITLE
Count of RSVPs

### ISSUE THREAD

**Issue by crespire** [radiushq/feature-requests#9]
On the event display for an organizer, it'd be nice to have a count of the RSVPs somewhere in the header area for that section:
<img width="438" alt="image" src="https://github.com/radiushq/feature-requests/assets/36272822/efc4fdbd-8d53-4948-94c2-4f7fa1ebe7d0">

**Comment by crespire** [comment]
I see that this change is live 🎉🎉🎉

**Comment by smuui** [comment]
Thanks for the request @crespire!  Will try to update issues in here as things progress 👍
